#!/usr/bin/python

from optparse import OptionParser
import commands



def read_file( file_name ):
    file = open( file_name, 'r' )
    lines = file.readlines()
    file.close()
    return lines



def show_swap_of_process( pid, options ):
    if options.verbose: print 'PID: %s' % pid
    lines = read_file( '/proc/%s/status' % pid )
    for line in lines:
	if line.startswith( 'VmSwap:' ):
	    swap = line.split( ' ' )[ 7 ]
	    if options.short: print '%s %s' % ( pid, swap )
	    else: print 'Process %s uses %s kB swap memory.' % ( pid, swap )
	    return int( swap )



def cli():
    usage = 'usage: %prog [options] pid [pid...]'
    parser = OptionParser( usage = usage )
    parser.add_option( '-v', '--verbose', action = 'store_true', dest = 'verbose', help = 'Show additional output messages.' )
    ( options, args ) = parser.parse_args()
    return ( options, args )



def main():
    ( options, args ) = cli()
    size = args[ 0 ]
    commands.getoutput( 'mkdir /tmp/ramdisk; chmod 777 /tmp/ramdisk' )
    output = commands.getoutput( 'sudo mount -t tmpfs -o -size=%s tmpfs /tmp/ramdisk' % size )
    print output



main()
