#!/usr/bin/python

from optparse import OptionParser



def read_file( file_name ):
    file = open( file_name, 'r' )
    lines = file.readlines()
    file.close()
    return lines



def show_swap_of_process( pid, options ):
    if options.verbose: print 'PID: %s' % pid
    lines = read_file( '/proc/%s/status' % pid )
    for line in lines:
	if line.startswith( 'VmSwap:' ):
	    swap = line.split( ' ' )[ 7 ]
	    if options.short: print '%s %s' % ( pid, swap )
	    else: print 'Process %s uses %s kB swap memory.' % ( pid, swap )



def cli():
    parser = OptionParser()
    parser.add_option( '-s', '--short', action = 'store_true', dest = 'short' )
    parser.add_option( '-v', '--verbose', action = 'store_true', dest = 'verbose' )
    ( options, args ) = parser.parse_args()
    return ( options, args )



def main():
    ( options, args ) = cli()
    for pid in args:
	show_swap_of_process( pid, options )
    
    



main()
